### ISSUE TITLE
milestone 2 feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_04_anh_eve#27]
Awesome work!

tiny issue:
- readme file: please use rmarkdown features to make it look better. for example, check how to edit things that are code (inline or as a chunk of codes to run). for example [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by evelynjulia** [comment]
Thanks! We have done so :)
