### ISSUE TITLE
Package to install to knit pdf

### ISSUE THREAD

**Issue by Anh-NguyetLe** [STAT547-UBC-2019-20/group_04_anh_eve#30]
To Eve:

Copy paste these codes below to your console and run the command line for Knit.R in the terminal again. The pdf should be knitted now. 

install.packages("webshot")
webshot::install_phantomjs()

[Source](https://bookdown.org/yihui/bookdown/html-widgets.html)

**Comment by evelynjulia** [comment]
Thank you!
