### ISSUE TITLE
Assignment 3 - Review of Group 04

### ISSUE THREAD

**Issue by sciclic** [STAT547-UBC-2019-20/group_04_anh_eve#37]
Hi Ahn & Eve,

I've been assigned your group to review as part of Assignment 3. Please find my feedback below, and let me know if you have any questions:

### Task 1

Following the **usage** instructions in your repo [README](https://github.com/STAT547-UBC-2019-20/group_04_anh_eve/blob/master/README.md), I cloned your repository and attempted to run the scripts, but I had the following error:

```
C:\Users\iciar\OneDrive\Desktop\School\STAT547\group_04_ahn_eve\Scripts>rscript load_data.R --url="https://raw.githubusercontent.com/STAT547-UBC-2019-20/data_sets/master/airquality.csv" --outfilename="aq.csv"
Error: unexpected symbol in:
"
Usage: load_data.R --url="https"
Execution halted
```
I then tried to run it with "http" instead of "https" because I have gotten similar errors before (I am working from a Windows, and apparently this can be an issue), but still no luck. I tried to run it without quotes "" because it says unexpected symbol, but still not working. I definitely think this is an issue on my end and not yours, and I read through your scripts and they seem well-written and implement functions and docopt() requirements correctly, so this should be only due to some needed troubleshooting on my end.

### Task 2

- The dataset you chose is very complete. From my own experience on this project I wish I had chosen a dataset with more numerical observations like yours! 

- The report is well structured and easy to follow, I like that you added a  methods section clearly outline the steps that are taken in the analysis, and that your tables look very clean.

- Your chosen methods for EDA and linear regression analysis make sense with the question you are attempting to answer, and I personally found **graph 2** quite interesting, I wouldn't have thought that some gases (benzene) would have essentially no variation over time. From my understanding benzene primarily originates from gasoline service stations and other industrial activities - I wonder if the levels would vary over time in rural vs. urban areas but I know this data is not available for you.

- I like that the comments with each graph are brief and concise but provide some context.

**Comment by evelynjulia** [comment]
Thanks so much for your feedback! Sorry it didn't seem to work on your computer... I wonder what it must be. It seems that it works on most other computers so hopefully there is nothing wrong on our side. 

We appreciate the feedback anyway!

**Comment by yuliaUU** [comment]
it seems that `https` was a problem, try and replace it with `http`
if this issue was not fixed, you should have referenced it in the new issue and labeled future work, not just close it.
