### ISSUE TITLE
Assignment 3- Group 4 Review 

### ISSUE THREAD

**Issue by Deni678** [STAT547-UBC-2019-20/group_04_anh_eve#40]
Overall, the repository is very well organized. Directories are clearly labeled and files within folders also have informative names. It might be beneficial to add a README.md file for each directory with a basic description of what is contained within that directory.

In your code, error checking for invalid input would be useful.
The Usage section on the project README was easy to understand and follow. One minor modification is that in the usage for load_data.R it would be good to  eliminate the space between — and <outfile> because it throws an error.
The scripts  load_data.R, clean_data.R EDA.R executed and ran to completion  and the output is as expected.The clean_data.R script executes as expected.The EDA.R script works but it displays warning messages that you might want to suppress in your code so that the user does not see them.
Functions and scripts are clearly written and well-documented. In the clean_data.R script there is some “dead” code that you might want to remove to make the script cleaner. In addition, some more comments in the LinearRegression.R script might be beneficial for the user to have a clearer understanding of what the purpose of the code is. The analysis does not take long to run.
On the group README.md, the link to the report for Milestone 1 does not seem to be working.

Good motivation and interesting research question. The visualizations are effective, eye-catching and easy to understand. However, it is a bit difficult to see a pattern in the scatterplot of temp vs benzene- maybe a line chart would have been more appropriate. The Pollutant vs Time graph is very informative and easy to understand.

**Comment by evelynjulia** [comment]
Hey! Thanks for your feedback! We really appreciate it and the encouragement as well. 

We plan to make changes to most of the things you've mentioned!
