### ISSUE TITLE
Feedback Milestone 4

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_04_anh_eve#54]
Hi!
Your Dashboard looks pretty straightforward and clean!

Couple things:
- It would be best if "daily distribution of pollutants " graph will get updated without its own dropdown to select the pollutant. you already have that dropdown for your first graph
- the sidebar was not explained: what is it for? is it a specific day or range/ than what does the averaging period do?
- make sure to make some space for explaining why you  created this dashboard ( you can utilize the stuff from your final report's intro section) and also acknowledge the data source

Feedback:
- I could not figure out which feedback was implemented and which was not

**Comment by evelynjulia** [comment]
Thanks @yuliaUU !
All graphs depend on the same dropdown
The sidebar is now used for the dropdown menus
We've included a description at the top of the dashboard and I've added the data source.
